"""
ONNX export — emit a QAT model as a graph TensorRT can build an INT8 engine from.

The exported graph carries ``QuantizeLinear``/``DequantizeLinear`` pairs holding
the ranges learned during QAT. TensorRT reads those directly, so no calibration
cache is needed at build time — that is the deployment payoff of QAT over PTQ.

Two things the original implementation got wrong
------------------------------------------------
**Detect head output.** It exported the raw ``DetectionModel``. In eval mode the
detect head returns a *tuple* ``(y, x)``, so the graph came out with several
outputs while ``output_names=["output0"]`` named only the first; the rest got
autogenerated names and DeepStream could not find them. Ultralytics sets
``Detect.export = True`` and ``Detect.format = "onnx"`` precisely to collapse
this to one ``output0`` of shape ``(batch, 4 + nc, anchors)``. Verified on
yolov8s: ``(1, 84, 8400)``.

**Opset.** The config asked for 17. Q/DQ export is specified against **opset 13**,
which is what NVIDIA documents and what TensorRT's parser is tested against.

Never run onnx-simplifier on the result — it folds Q/DQ pairs away and you
silently get an FP32 graph back.
"""

from __future__ import annotations

import collections
import copy
import inspect
import logging
import os
from typing import Any, Dict, List, Optional, Tuple

import onnx
import torch
import torch.nn as nn

from .qat_quantize import assert_qat_active
from .utils import ensure_dir

logger = logging.getLogger("YOLO_QAT")

_QDQ_OPS = {"QuantizeLinear", "DequantizeLinear"}


def _set_detect_export_mode(model: nn.Module, export: bool, fmt: Optional[str]) -> None:
    """
    Flip the detect head between training-style and export-style outputs.

    Matches by class name rather than isinstance so it covers Detect and every
    subclass (Segment, Pose, OBB, v10Detect) without importing each one.
    """
    for module in model.modules():
        if "Detect" in type(module).__name__ and hasattr(module, "export"):
            module.export = export
            if hasattr(module, "format"):
                module.format = fmt


def _supports_kwarg(fn: Any, name: str) -> bool:
    """True if ``fn`` accepts the given keyword argument."""
    try:
        return name in inspect.signature(fn).parameters
    except (TypeError, ValueError):  # pragma: no cover
        return False


def export_qat_onnx(
    model: nn.Module,
    onnx_path: str,
    imgsz: Tuple[int, int] = (640, 640),
    opset: int = 13,
    device: torch.device = torch.device("cpu"),
    dynamic_batch: bool = False,
    max_batch: int = 8,
    fuse: bool = True,
) -> str:
    """
    Export a quantization-aware model to ONNX with Q/DQ nodes.

    Args:
        model: The QAT-trained model.
        onnx_path: Output path.
        imgsz: ``(height, width)`` of the export input.
        opset: ONNX opset. 13 is what Q/DQ export is specified against.
        device: Device to trace on.
        dynamic_batch: Emit a dynamic batch dimension.
        max_batch: Documented upper batch bound (used by the engine builder).
        fuse: Fold BatchNorm into the preceding conv before export. Ultralytics
            rescales each weight quantizer's range by the folding factor, so the
            INT8 codes are unchanged and TensorRT gets a smaller graph.

    Returns:
        The path written.
    """
    assert_qat_active(model, context="ONNX export")

    parent = os.path.dirname(os.path.abspath(onnx_path))
    ensure_dir(parent)

    # Export from a copy: fuse() and the export flags mutate the model in place,
    # and the caller may still want to train or evaluate afterwards.
    export_model = copy.deepcopy(model).float().eval().to(device)

    if fuse and hasattr(export_model, "fuse"):
        try:
            export_model = export_model.fuse(verbose=False)
            logger.info("Folded BatchNorm into preceding convolutions")
        except (RuntimeError, TypeError, AttributeError) as exc:
            logger.warning("BatchNorm folding failed (%s); exporting unfused", exc)

    for param in export_model.parameters():
        param.requires_grad_(False)

    _set_detect_export_mode(export_model, export=True, fmt="onnx")

    dummy = torch.zeros(1, 3, imgsz[0], imgsz[1], device=device)

    # Confirm the head really collapsed to a single tensor before tracing.
    with torch.no_grad():
        probe = export_model(dummy)
    if not torch.is_tensor(probe):
        raise RuntimeError(
            f"Detect head returned {type(probe).__name__}, expected a single Tensor. "
            "Export mode did not take effect; the ONNX would have mismatched outputs."
        )
    logger.info("Export-mode output shape: %s", tuple(probe.shape))

    dynamic_axes: Optional[Dict[str, Dict[int, str]]] = None
    if dynamic_batch:
        dynamic_axes = {"images": {0: "batch"}, "output0": {0: "batch"}}

    export_kwargs: Dict[str, Any] = {
        "opset_version": opset,
        "input_names": ["images"],
        "output_names": ["output0"],
        "do_constant_folding": True,
    }
    if dynamic_axes is not None:
        export_kwargs["dynamic_axes"] = dynamic_axes
    # torch >= 2.6 defaults to the dynamo exporter. Q/DQ symbolic export is
    # defined for the legacy TorchScript path, which is what TensorRT expects.
    if _supports_kwarg(torch.onnx.export, "dynamo"):
        export_kwargs["dynamo"] = False

    logger.info("Exporting ONNX -> %s (opset=%d, dynamic_batch=%s)", onnx_path, opset, dynamic_batch)
    torch.onnx.export(export_model, dummy, onnx_path, **export_kwargs)

    _validate_onnx(onnx_path, dynamic_batch=dynamic_batch, max_batch=max_batch)
    return onnx_path


def _validate_onnx(onnx_path: str, dynamic_batch: bool = False, max_batch: int = 8) -> Dict[str, Any]:
    """
    Check the exported graph and refuse to pass off an FP32 model as QAT.

    A missing-Q/DQ export is the failure this project is most exposed to: every
    downstream step still "succeeds", TensorRT builds a perfectly good FP32
    engine, and nothing reveals the problem until someone benchmarks it.
    """
    graph = onnx.load(onnx_path)
    onnx.checker.check_model(graph)

    counts = collections.Counter(node.op_type for node in graph.graph.node)
    qdq = sum(counts[op] for op in _QDQ_OPS)

    if qdq == 0:
        raise RuntimeError(
            f"{onnx_path} contains no QuantizeLinear/DequantizeLinear nodes.\n"
            "This is an FP32 graph, not a QAT one - TensorRT would build an FP32 "
            "engine from it. Check that quantization survived training and that "
            "no simplifier ran over the graph."
        )

    outputs: List[Tuple[str, List[Any]]] = [
        (o.name, [d.dim_value or d.dim_param for d in o.type.tensor_type.shape.dim])
        for o in graph.graph.output
    ]
    if len(outputs) != 1:
        logger.warning(
            "Expected exactly 1 output for DeepStream, found %d: %s",
            len(outputs),
            [name for name, _ in outputs],
        )

    size_mb = os.path.getsize(onnx_path) / (1024 * 1024)
    logger.info(
        "ONNX OK: %d nodes, %d QuantizeLinear + %d DequantizeLinear, %.1f MB",
        len(graph.graph.node),
        counts["QuantizeLinear"],
        counts["DequantizeLinear"],
        size_mb,
    )
    logger.info("Output(s): %s", outputs)
    logger.info("Do NOT run onnx-simplifier on this file - it strips Q/DQ nodes.")

    return {
        "qdq_nodes": qdq,
        "total_nodes": len(graph.graph.node),
        "outputs": outputs,
        "size_mb": size_mb,
    }
